name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: ["3.2"]
        ghc:
          - "8.8.3"
          - "8.10.1"
    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - name: Setup Haskell
      uses: actions/setup-haskell@v1.1.1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Freeze
      run: cabal freeze

    - name: Cache ~/.cabal/store
      uses: actions/cache@v1
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Build
      run: cabal build all

  static_analysis:
    needs: [build]
    name: Stan Static Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Setup Stan
      id: stan
      uses: kowainik/stan-action@8283a41b868860959941f8cf7d4323b000882a9d

    - name: Run Stan
      run: |
        echo ${{ steps.stan.outputs.stanPath }}
        echo $PATH
        ${{ steps.stan.outputs.stanPath }}
        stan
